import express from "express";

const app = express();
const PORT = 3001;

app.get("/produtos", (req, res) => {
  res.json([
    {
        "codigoproduto": 93474,
        "descricaoproduto": "CACAU PO 100% 500G GENUINE",
        "embalagem": "UNIDADE",
        "ultimopreco": "40.29",
        "quantidadefaturada": 22,
        "participacao": 2.92,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/03/2025 00:00:00"
    },
    {
        "codigoproduto": 105247,
        "descricaoproduto": "BATATA 9MM 2KG CG TUCHE",
        "embalagem": "PACOTE",
        "ultimopreco": "9.19",
        "quantidadefaturada": 70,
        "participacao": 0.81,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "08/25/2022 00:00:00"
    },
    {
        "codigoproduto": 83556,
        "descricaoproduto": "ARROZ ARBORIO P/RISOTO 1KG DI MATTEO",
        "embalagem": "PC",
        "ultimopreco": "15.4",
        "quantidadefaturada": 146,
        "participacao": 0.49,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/28/2022 00:00:00"
    },
    {
        "codigoproduto": 124016,
        "descricaoproduto": "ARROZ ARBORIO ITALIANO 1KG OPERA I",
        "embalagem": "UNIDADE",
        "ultimopreco": "18.88",
        "quantidadefaturada": 340,
        "participacao": 3.41,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "06/22/2023 00:00:00"
    },
    {
        "codigoproduto": 93259,
        "descricaoproduto": "ARROZ ARBORIO CULINARIA ITALIANA 1KG CAM",
        "embalagem": "UNIDADE",
        "ultimopreco": "22.92",
        "quantidadefaturada": 46,
        "participacao": 0.65,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "11/18/2024 00:00:00"
    },
    {
        "codigoproduto": 87374,
        "descricaoproduto": "QUEIJO PARM RALADO FINO 1KG SANTA MARTA",
        "embalagem": "UNIDADE",
        "ultimopreco": "29.9",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "08/01/2024 00:00:00"
    },
    {
        "codigoproduto": 86837,
        "descricaoproduto": "MOLHO SHOYU 900ML PIRATA",
        "embalagem": "UNIDADE",
        "ultimopreco": "10.7",
        "quantidadefaturada": 10,
        "participacao": 0.49,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/21/2025 00:00:00"
    },
    {
        "codigoproduto": 93268,
        "descricaoproduto": "ARROZ ARBORIO 1KG MEU BIJU",
        "embalagem": "CX C/10 UN",
        "ultimopreco": "24.13",
        "quantidadefaturada": 75,
        "participacao": 1.14,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "08/14/2023 00:00:00"
    },
    {
        "codigoproduto": 85454,
        "descricaoproduto": "FERMENTO BIOLOGICO INST MD 500G FLEISC",
        "embalagem": "UNIDADE",
        "ultimopreco": "17.25",
        "quantidadefaturada": 4,
        "participacao": 0.65,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "08/11/2022 00:00:00"
    },
    {
        "codigoproduto": 134909,
        "descricaoproduto": "AMIDO DE MILHO 1KG FRITZ E FRIDA",
        "embalagem": "UNIDADE",
        "ultimopreco": "6.66",
        "quantidadefaturada": 5,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "12/22/2022 00:00:00"
    },
    {
        "codigoproduto": 159020,
        "descricaoproduto": "VG BROCOLIS PCT 2KG CG CONF NAC",
        "embalagem": "QUILO",
        "ultimopreco": "12.99",
        "quantidadefaturada": 170,
        "participacao": 2.44,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/14/2025 00:00:00"
    },
    {
        "codigoproduto": 98457,
        "descricaoproduto": "LINGUICA CALABRESA RETA 2,5KG RF REZENDE",
        "embalagem": "PACOTE",
        "ultimopreco": "20.99",
        "quantidadefaturada": 62,
        "participacao": 1.14,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "12/11/2024 00:00:00"
    },
    {
        "codigoproduto": 116391,
        "descricaoproduto": "LEITE UHT INTEG 1L ITALAC",
        "embalagem": "UNIDADE",
        "ultimopreco": "4.79",
        "quantidadefaturada": 36,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "05/22/2023 00:00:00"
    },
    {
        "codigoproduto": 87325,
        "descricaoproduto": "CACAU PO 100% ALCALINO 500G SICAO",
        "embalagem": "UN",
        "ultimopreco": "31",
        "quantidadefaturada": 8,
        "participacao": 1.3,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "08/03/2023 00:00:00"
    },
    {
        "codigoproduto": 91407,
        "descricaoproduto": "MAIONESE BAG 2,8KG HELLMANNS",
        "embalagem": "UNIDADE",
        "ultimopreco": "45.99",
        "quantidadefaturada": 14,
        "participacao": 0.97,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/31/2025 00:00:00"
    },
    {
        "codigoproduto": 84477,
        "descricaoproduto": "LEITE COCO VD 500ML VIVANDA",
        "embalagem": "UNIDADE",
        "ultimopreco": "7.89",
        "quantidadefaturada": 3,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "06/02/2025 00:00:00"
    },
    {
        "codigoproduto": 124042,
        "descricaoproduto": "CHOC AMARGO 70% GOTA 400G UNIQUE",
        "embalagem": "UNIDADE",
        "ultimopreco": "33.4",
        "quantidadefaturada": 6,
        "participacao": 0.65,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "08/28/2023 00:00:00"
    },
    {
        "codigoproduto": 103474,
        "descricaoproduto": "MILHO VERDE LATA 1,7KG TRADELLI",
        "embalagem": "UNIDADE",
        "ultimopreco": "26.89",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "08/22/2022 00:00:00"
    },
    {
        "codigoproduto": 134752,
        "descricaoproduto": "REQUEIJAO C/AMIDO BISNAGA 1,8KG DALLORA",
        "embalagem": "UNIDADE",
        "ultimopreco": "23.48",
        "quantidadefaturada": 9,
        "participacao": 0.49,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "03/21/2024 00:00:00"
    },
    {
        "codigoproduto": 11106,
        "descricaoproduto": "OLEO DE ALGODAO 14,5KG/15,8L LIZA",
        "embalagem": "UNIDADE",
        "ultimopreco": "165.99",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/04/2024 00:00:00"
    },
    {
        "codigoproduto": 112391,
        "descricaoproduto": "CHOC MEIO AMARGO MOEDA 1,01KG HERSHEY",
        "embalagem": "UNIDADE",
        "ultimopreco": "49.72",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "08/21/2023 00:00:00"
    },
    {
        "codigoproduto": 102759,
        "descricaoproduto": "LEITE UHT INTEG ZERO LAC 1L ITAMBE",
        "embalagem": "UNIDADE",
        "ultimopreco": "7.16",
        "quantidadefaturada": 468,
        "participacao": 5.36,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "09/04/2023 00:00:00"
    },
    {
        "codigoproduto": 85043,
        "descricaoproduto": "COMP LACTEO VITAMINAS 1KG PURELAC",
        "embalagem": "UNIDADE",
        "ultimopreco": "31.41",
        "quantidadefaturada": 605,
        "participacao": 22.4,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/28/2025 00:00:00"
    },
    {
        "codigoproduto": 103007,
        "descricaoproduto": "CHOC MEIO A 40% G 2,05KG SI DUPLICACADO",
        "embalagem": "PACOTE",
        "ultimopreco": "85.2",
        "quantidadefaturada": 9,
        "participacao": 0.97,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "06/21/2023 00:00:00"
    },
    {
        "codigoproduto": 87483,
        "descricaoproduto": "LEITE COCO VD 500ML COCO DO VALE",
        "embalagem": "UNIDADE",
        "ultimopreco": "8",
        "quantidadefaturada": 2,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "03/06/2023 00:00:00"
    },
    {
        "codigoproduto": 83494,
        "descricaoproduto": "DESINF LAVANDA 5L BATUTA",
        "embalagem": "UNIDADE",
        "ultimopreco": "16.96",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "08/03/2023 00:00:00"
    },
    {
        "codigoproduto": 134893,
        "descricaoproduto": "ARROZ ARBORIO 1KG PILECCO NOBRE",
        "embalagem": "UNIDADE",
        "ultimopreco": "22.54",
        "quantidadefaturada": 238,
        "participacao": 1.95,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "08/22/2024 00:00:00"
    },
    {
        "codigoproduto": 102738,
        "descricaoproduto": "FARINHA DE ROSCA 5KG ORQUIDEA",
        "embalagem": "PACOTE",
        "ultimopreco": "66.38",
        "quantidadefaturada": 223,
        "participacao": 9.09,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/10/2025 00:00:00"
    },
    {
        "codigoproduto": 157195,
        "descricaoproduto": "ARROZ ARBORIO 1KG FRITZ E FRIDA",
        "embalagem": "UNIDADE",
        "ultimopreco": "18.29",
        "quantidadefaturada": 90,
        "participacao": 0.81,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "01/20/2025 00:00:00"
    },
    {
        "codigoproduto": 134903,
        "descricaoproduto": "ABACAXI RODELAS 400G FRITZ E FRIDA",
        "embalagem": "UNIDADE",
        "ultimopreco": "21.58",
        "quantidadefaturada": 3,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/28/2025 00:00:00"
    },
    {
        "codigoproduto": 88124,
        "descricaoproduto": "BACON CUBOS 1KG RF SOLETO",
        "embalagem": "PACOTE",
        "ultimopreco": "42.92",
        "quantidadefaturada": 54,
        "participacao": 1.95,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "03/07/2025 00:00:00"
    },
    {
        "codigoproduto": 89096,
        "descricaoproduto": "CREME DE LEITE 10% 1,01KG TRIANGULO",
        "embalagem": "UNIDADE",
        "ultimopreco": "13.81",
        "quantidadefaturada": 38,
        "participacao": 0.65,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "06/05/2025 00:00:00"
    },
    {
        "codigoproduto": 85185,
        "descricaoproduto": "VINHO BRANCO SECO C/CONDIM 750ML COOK WI",
        "embalagem": "UNIDADE",
        "ultimopreco": "20.65",
        "quantidadefaturada": 4,
        "participacao": 0.49,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "06/27/2025 00:00:00"
    },
    {
        "codigoproduto": 160534,
        "descricaoproduto": "FAROFA MILHO 250G FRITZ E FRIDA",
        "embalagem": "PACOTE",
        "ultimopreco": "3.64",
        "quantidadefaturada": 39,
        "participacao": 0.97,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/31/2025 00:00:00"
    },
    {
        "codigoproduto": 4009,
        "descricaoproduto": "LINGUICA CALABRESA CURVA PCT 2,5KG SEARA",
        "embalagem": "PACOTE",
        "ultimopreco": "28.18",
        "quantidadefaturada": 95,
        "participacao": 1.62,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/10/2025 00:00:00"
    },
    {
        "codigoproduto": 10586,
        "descricaoproduto": "AMACIANTE CARNE 1,01KG QUALIMAX",
        "embalagem": "UNIDADE",
        "ultimopreco": "17.46",
        "quantidadefaturada": 5,
        "participacao": 0.49,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "05/09/2022 00:00:00"
    },
    {
        "codigoproduto": 118922,
        "descricaoproduto": "SANITIZANTE CLORADO PO P FRUT VERD 3,6K",
        "embalagem": "UNIDADE",
        "ultimopreco": "78.12",
        "quantidadefaturada": 5,
        "participacao": 0.81,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/08/2024 00:00:00"
    },
    {
        "codigoproduto": 342,
        "descricaoproduto": "MILHO VERDE 1,7KG BONARE",
        "embalagem": "UNIDADE",
        "ultimopreco": "32.98",
        "quantidadefaturada": 2,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "12/26/2022 00:00:00"
    },
    {
        "codigoproduto": 113787,
        "descricaoproduto": "PIMENTA BIQUINHO 2KG CHEFF D CASA",
        "embalagem": "BALDE",
        "ultimopreco": "92.48",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "08/22/2024 00:00:00"
    },
    {
        "codigoproduto": 134963,
        "descricaoproduto": "POLVILHO DOCE 500G FRITZ E FRIDA",
        "embalagem": "UNIDADE",
        "ultimopreco": "5.74",
        "quantidadefaturada": 60,
        "participacao": 0.65,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/28/2025 00:00:00"
    },
    {
        "codigoproduto": 10500,
        "descricaoproduto": "MAIONESE 3KG MARIANA",
        "embalagem": "UNIDADE",
        "ultimopreco": "28.78",
        "quantidadefaturada": 2,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "06/02/2025 00:00:00"
    },
    {
        "codigoproduto": 86642,
        "descricaoproduto": "PAPEL HIG FOLHA SIMPLES BRANCO 8X300M",
        "embalagem": "UNIDADE",
        "ultimopreco": "36.06",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/28/2022 00:00:00"
    },
    {
        "codigoproduto": 134911,
        "descricaoproduto": "ARROZ BRANCO PREMIUM 1KG FRITZ E FRIDA",
        "embalagem": "UNIDADE",
        "ultimopreco": "5.99",
        "quantidadefaturada": 20,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/28/2025 00:00:00"
    },
    {
        "codigoproduto": 87239,
        "descricaoproduto": "ARROZ AGULHINHA TIPO1 5KG ALEGRETE",
        "embalagem": "UNIDADE",
        "ultimopreco": "21.57",
        "quantidadefaturada": 18,
        "participacao": 0.49,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "11/10/2022 00:00:00"
    },
    {
        "codigoproduto": 87375,
        "descricaoproduto": "QUEIJO RALADO GROSSO 1KG ITAMONTE",
        "embalagem": "UNIDADE",
        "ultimopreco": "60.84",
        "quantidadefaturada": 4,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "08/12/2024 00:00:00"
    },
    {
        "codigoproduto": 83326,
        "descricaoproduto": "SANITIZANTE CLORADO PO P/FRUT/VERD 1KG",
        "embalagem": "UNIDADE",
        "ultimopreco": "17.73",
        "quantidadefaturada": 2,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "06/13/2022 00:00:00"
    },
    {
        "codigoproduto": 93625,
        "descricaoproduto": "COMP LACTEO PROFISSIONAL 1KG ITAMBE",
        "embalagem": "PACOTE",
        "ultimopreco": "30.19",
        "quantidadefaturada": 25,
        "participacao": 1.46,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "05/31/2023 00:00:00"
    },
    {
        "codigoproduto": 112392,
        "descricaoproduto": "CHOC MEIO AMARGO MOEDA 40% 2,01KG HERSHE",
        "embalagem": "UNIDADE",
        "ultimopreco": "76.52",
        "quantidadefaturada": 23,
        "participacao": 2.76,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/16/2024 00:00:00"
    },
    {
        "codigoproduto": 81747,
        "descricaoproduto": "LEMON PEPPER 500G LG FOODS",
        "embalagem": "UNIDADE",
        "ultimopreco": "34.63",
        "quantidadefaturada": 19,
        "participacao": 2.11,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/28/2025 00:00:00"
    },
    {
        "codigoproduto": 110872,
        "descricaoproduto": "CHOC M AMARGO GOTA 70% 1,01K DUPLIC",
        "embalagem": "UNIDADE",
        "ultimopreco": "55.03",
        "quantidadefaturada": 2,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "03/23/2023 00:00:00"
    },
    {
        "codigoproduto": 99085,
        "descricaoproduto": "VG BROCOLIS 2KG CG GRANO",
        "embalagem": "PACOTE",
        "ultimopreco": "18.35",
        "quantidadefaturada": 4,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "02/02/2023 00:00:00"
    },
    {
        "codigoproduto": 158300,
        "descricaoproduto": "BACON CUBOS 1KG CG PERDIGAO",
        "embalagem": "PACOTE",
        "ultimopreco": "37.03",
        "quantidadefaturada": 31,
        "participacao": 1.46,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "05/22/2025 00:00:00"
    },
    {
        "codigoproduto": 136040,
        "descricaoproduto": "MOLHO TOMATE TRAD 2KG QUERO",
        "embalagem": "UNIDADE",
        "ultimopreco": "12.5",
        "quantidadefaturada": 2,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "06/05/2025 00:00:00"
    },
    {
        "codigoproduto": 88228,
        "descricaoproduto": "EMB TRUFA/BOMBOM OURO 14,5X15,5CM 100UN",
        "embalagem": "UNIDADE",
        "ultimopreco": "10.94",
        "quantidadefaturada": 8,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/28/2022 00:00:00"
    },
    {
        "codigoproduto": 94480,
        "descricaoproduto": "ESPONJA LIMPEZA BETTACO 87X125MM 10UN BE",
        "embalagem": "UNIDADE",
        "ultimopreco": "28.06",
        "quantidadefaturada": 4,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/25/2024 00:00:00"
    },
    {
        "codigoproduto": 93027,
        "descricaoproduto": "ABACAXI RODELAS CALDA 400G TRIANGULO",
        "embalagem": "UNIDADE",
        "ultimopreco": "20.51",
        "quantidadefaturada": 8,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/01/2025 00:00:00"
    },
    {
        "codigoproduto": 136796,
        "descricaoproduto": "LEITE UHT INTEG C/TAMPA 1L UAI",
        "embalagem": "UNIDADE",
        "ultimopreco": "4.09",
        "quantidadefaturada": 36,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "11/24/2022 00:00:00"
    },
    {
        "codigoproduto": 83838,
        "descricaoproduto": "CHOC BRANCO DIET 500G DIATT",
        "embalagem": "UNIDADE",
        "ultimopreco": "52.32",
        "quantidadefaturada": 2,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "11/21/2022 00:00:00"
    },
    {
        "codigoproduto": 116623,
        "descricaoproduto": "AZEITE DENDE 900ML CEPERA",
        "embalagem": "UNIDADE",
        "ultimopreco": "29.81",
        "quantidadefaturada": 2,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "03/06/2023 00:00:00"
    },
    {
        "codigoproduto": 157249,
        "descricaoproduto": "ACUCAR CRISTAL SACHE 1000X5G GUARANI",
        "embalagem": "CAIXA",
        "ultimopreco": "41.59",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/22/2025 00:00:00"
    },
    {
        "codigoproduto": 118435,
        "descricaoproduto": "COMP LACTEO CULINARIO 1KG PURELAC",
        "embalagem": "UNIDADE",
        "ultimopreco": "19.93",
        "quantidadefaturada": 5,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "05/05/2022 00:00:00"
    },
    {
        "codigoproduto": 120890,
        "descricaoproduto": "VG ERVILHA IQF 1,01KG CG CONFRESCOR",
        "embalagem": "PACOTE",
        "ultimopreco": "19.17",
        "quantidadefaturada": 6,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "10/23/2024 00:00:00"
    },
    {
        "codigoproduto": 136615,
        "descricaoproduto": "CHOC M AMARGO GOTAS 400G MELKEN",
        "embalagem": "UNIDADE",
        "ultimopreco": "36.98",
        "quantidadefaturada": 5,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/28/2025 00:00:00"
    },
    {
        "codigoproduto": 82603,
        "descricaoproduto": "QUINOA EM GRAOS 200G NATUREZA VIVA",
        "embalagem": "UNIDADE",
        "ultimopreco": "10.89",
        "quantidadefaturada": 3,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/21/2025 00:00:00"
    },
    {
        "codigoproduto": 154075,
        "descricaoproduto": "AZEITE OLIVA EXT VRG 5L OPERA NAC",
        "embalagem": "GALAO",
        "ultimopreco": "426.54",
        "quantidadefaturada": 2,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "06/02/2025 00:00:00"
    },
    {
        "codigoproduto": 71330,
        "descricaoproduto": "MILHO VERDE 1,7KG MINAS MAIS",
        "embalagem": "LATA",
        "ultimopreco": "21.79",
        "quantidadefaturada": 5,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "06/02/2025 00:00:00"
    },
    {
        "codigoproduto": 95899,
        "descricaoproduto": "ACUCAR SACHE 1000X5G GUARANI",
        "embalagem": "CAIXA",
        "ultimopreco": "23.9",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "02/24/2022 00:00:00"
    },
    {
        "codigoproduto": 157992,
        "descricaoproduto": "VG ERVILHA IQF 2KG CG CONFRESCOR",
        "embalagem": "QUILO",
        "ultimopreco": "17.67",
        "quantidadefaturada": 10,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "03/27/2024 00:00:00"
    },
    {
        "codigoproduto": 87112,
        "descricaoproduto": "CHIMICHURRI 500G AZP",
        "embalagem": "UNIDADE",
        "ultimopreco": "23.01",
        "quantidadefaturada": 2,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "06/27/2022 00:00:00"
    },
    {
        "codigoproduto": 87454,
        "descricaoproduto": "PASTA AMENDOIM INTEG 450G AMENDOREI",
        "embalagem": "UNIDADE",
        "ultimopreco": "13.45",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "12/22/2022 00:00:00"
    },
    {
        "codigoproduto": 84485,
        "descricaoproduto": "COCO RALADO FINO S/ACUCAR DESIDRA 1KG IN",
        "embalagem": "UNIDADE",
        "ultimopreco": "30.79",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "06/21/2023 00:00:00"
    },
    {
        "codigoproduto": 94553,
        "descricaoproduto": "DETERGENTE NEUTRO 5L LIMPOL",
        "embalagem": "UNIDADE",
        "ultimopreco": "26.26",
        "quantidadefaturada": 251,
        "participacao": 11.85,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/30/2025 00:00:00"
    },
    {
        "codigoproduto": 94341,
        "descricaoproduto": "FERMENTO QUIMICO PO 2KG FLEISCHMANN",
        "embalagem": "UNIDADE",
        "ultimopreco": "56.81",
        "quantidadefaturada": 2,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "11/10/2022 00:00:00"
    },
    {
        "codigoproduto": 116625,
        "descricaoproduto": "MOLHO BARBECUE 3,5KG CEPERA",
        "embalagem": "UNIDADE",
        "ultimopreco": "39.84",
        "quantidadefaturada": 8,
        "participacao": 1.3,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "01/16/2025 00:00:00"
    },
    {
        "codigoproduto": 83144,
        "descricaoproduto": "OREGANO 200G PIRATA",
        "embalagem": "UNIDADE",
        "ultimopreco": "18.9",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "05/09/2022 00:00:00"
    },
    {
        "codigoproduto": 10594,
        "descricaoproduto": "CALDO GALINHA BAG 1,01KG QUALIMAX",
        "embalagem": "UNIDADE",
        "ultimopreco": "15.54",
        "quantidadefaturada": 3,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "05/15/2024 00:00:00"
    },
    {
        "codigoproduto": 136441,
        "descricaoproduto": "CREME CULINARIO 20% 1KG RICH S",
        "embalagem": "UNIDADE",
        "ultimopreco": "13.59",
        "quantidadefaturada": 12,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "03/17/2025 00:00:00"
    },
    {
        "codigoproduto": 4221,
        "descricaoproduto": "LINGUICA CALABRESA DEF CURVA 2,5KG PERDI",
        "embalagem": "PACOTE",
        "ultimopreco": "27.7",
        "quantidadefaturada": 12,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/21/2025 00:00:00"
    },
    {
        "codigoproduto": 136838,
        "descricaoproduto": "OLEO ALGODAO 14,5KG CHEF&CO",
        "embalagem": "BALDE",
        "ultimopreco": "145.9",
        "quantidadefaturada": 5,
        "participacao": 0.81,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "03/21/2024 00:00:00"
    },
    {
        "codigoproduto": 134306,
        "descricaoproduto": "PREP SABOR CHEDDAR FAT 2,27KG OPERA",
        "embalagem": "UNIDADE",
        "ultimopreco": "40.07",
        "quantidadefaturada": 2,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "08/01/2022 00:00:00"
    },
    {
        "codigoproduto": 88012,
        "descricaoproduto": "OREGANO 270G ANTONELLA",
        "embalagem": "UNIDADE",
        "ultimopreco": "20.01",
        "quantidadefaturada": 4,
        "participacao": 0.49,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/14/2022 00:00:00"
    },
    {
        "codigoproduto": 83081,
        "descricaoproduto": "CHIMICHURRI C/PIMENTA 250G PACHA",
        "embalagem": "UNIDADE",
        "ultimopreco": "11.38",
        "quantidadefaturada": 11,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "03/31/2022 00:00:00"
    },
    {
        "codigoproduto": 120445,
        "descricaoproduto": "VG BROCOLIS IQF 1.01KG CG CONFRESCOR",
        "embalagem": "QUILO",
        "ultimopreco": "12.25",
        "quantidadefaturada": 15,
        "participacao": 0.49,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/16/2024 00:00:00"
    },
    {
        "codigoproduto": 91068,
        "descricaoproduto": "VG BROCOLIS 2,5KG CG NUTRIZ",
        "embalagem": "QUILO",
        "ultimopreco": "13.55",
        "quantidadefaturada": 15,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "03/18/2024 00:00:00"
    },
    {
        "codigoproduto": 133932,
        "descricaoproduto": "CREME LEITE 14% 1,01KG DAMARE",
        "embalagem": "UNIDADE",
        "ultimopreco": "15.05",
        "quantidadefaturada": 2,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "05/15/2024 00:00:00"
    },
    {
        "codigoproduto": 10291,
        "descricaoproduto": "REQ CREM CULINARIO 1,5KG RF CATUPIRY",
        "embalagem": "UNIDADE",
        "ultimopreco": "65.23",
        "quantidadefaturada": 14,
        "participacao": 0.65,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "08/27/2024 00:00:00"
    },
    {
        "codigoproduto": 4374,
        "descricaoproduto": "MOLHO SHOYU TRAD 5L MITSUWA",
        "embalagem": "UNIDADE",
        "ultimopreco": "83.88",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/04/2025 00:00:00"
    },
    {
        "codigoproduto": 85345,
        "descricaoproduto": "LEITE UHT INTEG 1L PIRACANJUBA",
        "embalagem": "UNIDADE",
        "ultimopreco": "4.82",
        "quantidadefaturada": 24,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "12/12/2022 00:00:00"
    },
    {
        "codigoproduto": 10588,
        "descricaoproduto": "AMIDO DE MILHO 1KG QUALIMAX",
        "embalagem": "UNIDADE",
        "ultimopreco": "9.15",
        "quantidadefaturada": 5,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "03/31/2022 00:00:00"
    },
    {
        "codigoproduto": 82871,
        "descricaoproduto": "AGUA SANITARIA 5L CLASSIC",
        "embalagem": "UNIDADE",
        "ultimopreco": "14.24",
        "quantidadefaturada": 5,
        "participacao": 0.81,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "08/03/2023 00:00:00"
    },
    {
        "codigoproduto": 81565,
        "descricaoproduto": "QUEIJO MUSSARELA 3,8KG RF DONA FORMOSA",
        "embalagem": "QUILO",
        "ultimopreco": "36.78",
        "quantidadefaturada": 22,
        "participacao": 0.65,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/23/2024 00:00:00"
    },
    {
        "codigoproduto": 84650,
        "descricaoproduto": "FARINHA TRIGO TP1 5KG GRAZIELLA",
        "embalagem": "PACOTE",
        "ultimopreco": "26.2",
        "quantidadefaturada": 6,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "03/31/2022 00:00:00"
    },
    {
        "codigoproduto": 83083,
        "descricaoproduto": "CANELA MOIDA PURA 500G PACHA",
        "embalagem": "UNIDADE",
        "ultimopreco": "46.86",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/28/2022 00:00:00"
    },
    {
        "codigoproduto": 87595,
        "descricaoproduto": "ARROZ AGULHINHA TIPO1 2KG ALEGRETE",
        "embalagem": "UNIDADE",
        "ultimopreco": "9.24",
        "quantidadefaturada": 13,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "01/13/2023 00:00:00"
    },
    {
        "codigoproduto": 85846,
        "descricaoproduto": "LEITE UHT INTEG 1L ITA",
        "embalagem": "UNIDADE",
        "ultimopreco": "5.23",
        "quantidadefaturada": 36,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "06/30/2025 00:00:00"
    },
    {
        "codigoproduto": 85419,
        "descricaoproduto": "PIMENTA BIQUINHO 2KG IMPERADOR",
        "embalagem": "UNIDADE",
        "ultimopreco": "73.59",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/12/2024 00:00:00"
    },
    {
        "codigoproduto": 156990,
        "descricaoproduto": "CHOC MEIO AMARGO 40% MOEDA 2,05KG SICAO",
        "embalagem": "PACOTE",
        "ultimopreco": "239.77",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/31/2025 00:00:00"
    },
    {
        "codigoproduto": 132946,
        "descricaoproduto": "FARINHA PANKO 1,01KG CHEFS OWN",
        "embalagem": "PACOTE",
        "ultimopreco": "29.26",
        "quantidadefaturada": 3,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/10/2025 00:00:00"
    },
    {
        "codigoproduto": 82385,
        "descricaoproduto": "AZEITE OLIVA EXT VRG 500ML VIVANDA",
        "embalagem": "UNIDADE",
        "ultimopreco": "21.26",
        "quantidadefaturada": 3,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "03/31/2022 00:00:00"
    },
    {
        "codigoproduto": 83016,
        "descricaoproduto": "AGUA SANITARIA 1L MARINA",
        "embalagem": "CX C/12 UN",
        "ultimopreco": "2.6",
        "quantidadefaturada": 12,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/28/2022 00:00:00"
    },
    {
        "codigoproduto": 87125,
        "descricaoproduto": "ARROZ AGULHINHA TIPO1 2KG CODIL",
        "embalagem": "UNIDADE",
        "ultimopreco": "15.2",
        "quantidadefaturada": 30,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "05/08/2024 00:00:00"
    },
    {
        "codigoproduto": 83086,
        "descricaoproduto": "FEIJAO CARIOCA TP1 1KG PACHA",
        "embalagem": "UNIDADE",
        "ultimopreco": "6.25",
        "quantidadefaturada": 10,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/25/2024 00:00:00"
    },
    {
        "codigoproduto": 84468,
        "descricaoproduto": "CAFE TRAD 500G TRES CORACOES",
        "embalagem": "UNIDADE",
        "ultimopreco": "34.49",
        "quantidadefaturada": 10,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/17/2025 00:00:00"
    },
    {
        "codigoproduto": 1144,
        "descricaoproduto": "CHOC MEIO AMARGO 2,1KG GENUINE",
        "embalagem": "UNIDADE",
        "ultimopreco": "78.75",
        "quantidadefaturada": 24,
        "participacao": 2.11,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "02/02/2023 00:00:00"
    },
    {
        "codigoproduto": 84309,
        "descricaoproduto": "OLEO SOJA PET 900ML CORCOVADO",
        "embalagem": "UNIDADE",
        "ultimopreco": "10.49",
        "quantidadefaturada": 20,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/28/2022 00:00:00"
    },
    {
        "codigoproduto": 133033,
        "descricaoproduto": "TOMATE PELADO LATA 2,5KG OPERA I",
        "embalagem": "CAIXA",
        "ultimopreco": "40.68",
        "quantidadefaturada": 4,
        "participacao": 0.65,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "10/13/2022 00:00:00"
    },
    {
        "codigoproduto": 136739,
        "descricaoproduto": "ARROZ ARBORIO ITALIANO 1KG OPERA N",
        "embalagem": "UNIDADE",
        "ultimopreco": "18.99",
        "quantidadefaturada": 1390,
        "participacao": 10.23,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "05/06/2025 00:00:00"
    },
    {
        "codigoproduto": 82049,
        "descricaoproduto": "TACA C/TAMPA 10X40ML BYWER",
        "embalagem": "UNIDADE",
        "ultimopreco": "9.86",
        "quantidadefaturada": 5,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/04/2024 00:00:00"
    },
    {
        "codigoproduto": 88680,
        "descricaoproduto": "FARINHA ROSCA 5KG PACHA",
        "embalagem": "UNIDADE",
        "ultimopreco": "60.77",
        "quantidadefaturada": 149,
        "participacao": 7.63,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/30/2025 00:00:00"
    },
    {
        "codigoproduto": 93476,
        "descricaoproduto": "CACAU PO 100% 500G MELKEN",
        "embalagem": "UNIDADE",
        "ultimopreco": "32.63",
        "quantidadefaturada": 24,
        "participacao": 3.08,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "05/21/2025 00:00:00"
    },
    {
        "codigoproduto": 157396,
        "descricaoproduto": "CACAU PO 100% ALCALINO 500G SICAO",
        "embalagem": "UNIDADE",
        "ultimopreco": "26.34",
        "quantidadefaturada": 2,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "10/24/2024 00:00:00"
    },
    {
        "codigoproduto": 156128,
        "descricaoproduto": "VG ERVILHA PCT IQF 2.5KG CG CONFRESCOR",
        "embalagem": "QUILO",
        "ultimopreco": "18.15",
        "quantidadefaturada": 60,
        "participacao": 0.97,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "05/28/2025 00:00:00"
    },
    {
        "codigoproduto": 161068,
        "descricaoproduto": "ACAI C/GRANOLA  200ML CG SPLIT TODO DIA",
        "embalagem": "CAIXA",
        "ultimopreco": "5.07",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "05/06/2025 00:00:00"
    },
    {
        "codigoproduto": 159821,
        "descricaoproduto": "FILTRO PAPEL P/CAFE 103 C/30UN FRITZ E F",
        "embalagem": "UNIDADE",
        "ultimopreco": "4.29",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "06/02/2025 00:00:00"
    },
    {
        "codigoproduto": 83112,
        "descricaoproduto": "CASTANHA CAJU GROSSA XEREM G2T 1KG KAJUN",
        "embalagem": "UNIDADE",
        "ultimopreco": "32.06",
        "quantidadefaturada": 6,
        "participacao": 0.97,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "12/26/2022 00:00:00"
    },
    {
        "codigoproduto": 83007,
        "descricaoproduto": "AGUA MINERAL NATURAL 510ML INGA",
        "embalagem": "FD C/12 UN",
        "ultimopreco": "1.5",
        "quantidadefaturada": 156,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "03/07/2024 00:00:00"
    },
    {
        "codigoproduto": 86315,
        "descricaoproduto": "LEITE UHT DESNATADO ZERO LACT 1L ITAMBE",
        "embalagem": "UNIDADE",
        "ultimopreco": "6.98",
        "quantidadefaturada": 24,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "06/02/2022 00:00:00"
    },
    {
        "codigoproduto": 82801,
        "descricaoproduto": "CREME CULINARIO 20% 1KG RICH DO BRAS",
        "embalagem": "UNIDADE",
        "ultimopreco": "12.49",
        "quantidadefaturada": 6,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/07/2022 00:00:00"
    },
    {
        "codigoproduto": 84979,
        "descricaoproduto": "LEITE UHT INTEG 1L PORTO ALEGRE",
        "embalagem": "UNIDADE",
        "ultimopreco": "5.42",
        "quantidadefaturada": 240,
        "participacao": 1.46,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "06/05/2025 00:00:00"
    },
    {
        "codigoproduto": 82601,
        "descricaoproduto": "BACON FAT EXTRA 1KG SADELLE",
        "embalagem": "PACOTE",
        "ultimopreco": "24.9",
        "quantidadefaturada": 7,
        "participacao": 0.81,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "10/24/2022 00:00:00"
    },
    {
        "codigoproduto": 84593,
        "descricaoproduto": "FARINHA MANDIOCA BRANCA 1KG PACHA",
        "embalagem": "FD C/10 UN",
        "ultimopreco": "4.79",
        "quantidadefaturada": 10,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/23/2024 00:00:00"
    },
    {
        "codigoproduto": 84174,
        "descricaoproduto": "CHOC AMARGO GOTA 70,5%CACAU 400G BARRY",
        "embalagem": "UNIDADE",
        "ultimopreco": "68.56",
        "quantidadefaturada": 4,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "10/21/2024 00:00:00"
    },
    {
        "codigoproduto": 87802,
        "descricaoproduto": "SABONETE LIQ NEUTRO PEROLADO 5L DUOMO",
        "embalagem": "UNIDADE",
        "ultimopreco": "19.43",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/26/2024 00:00:00"
    },
    {
        "codigoproduto": 87240,
        "descricaoproduto": "ARROZ AGULHINHA TIPO1 5KG CARRIJO",
        "embalagem": "UNIDADE",
        "ultimopreco": "20.44",
        "quantidadefaturada": 6,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "11/09/2022 00:00:00"
    },
    {
        "codigoproduto": 136565,
        "descricaoproduto": "COMP LACTEO CULINARIO 1KG PURELAC",
        "embalagem": "PACOTE",
        "ultimopreco": "28.81",
        "quantidadefaturada": 6,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "08/12/2024 00:00:00"
    },
    {
        "codigoproduto": 85301,
        "descricaoproduto": "DETERGENTE NEUTRO CONCENTRADO DN60 5L",
        "embalagem": "UNIDADE",
        "ultimopreco": "21.86",
        "quantidadefaturada": 2,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "05/23/2022 00:00:00"
    },
    {
        "codigoproduto": 8338,
        "descricaoproduto": "PEITO DE FRANGO DEF +-3KG RF SEARA",
        "embalagem": "QUILO",
        "ultimopreco": "39.69",
        "quantidadefaturada": 77,
        "participacao": 2.27,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "06/05/2025 00:00:00"
    },
    {
        "codigoproduto": 103001,
        "descricaoproduto": "CHOC MEIO AMARGO BARRA 2,1KG SICAO NOBRE",
        "embalagem": "UN",
        "ultimopreco": "75.99",
        "quantidadefaturada": 8,
        "participacao": 0.97,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "08/01/2022 00:00:00"
    },
    {
        "codigoproduto": 94556,
        "descricaoproduto": "DETERGENTE NEUTRO 5L YPE",
        "embalagem": "UNIDADE",
        "ultimopreco": "27.85",
        "quantidadefaturada": 262,
        "participacao": 13.64,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/03/2025 00:00:00"
    },
    {
        "codigoproduto": 134383,
        "descricaoproduto": "MILHO VERDE 1,7KG QUERO",
        "embalagem": "LATA",
        "ultimopreco": "21.79",
        "quantidadefaturada": 22,
        "participacao": 1.95,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/28/2025 00:00:00"
    },
    {
        "codigoproduto": 84645,
        "descricaoproduto": "ACUCAR CRISTAL 2KG MINAS",
        "embalagem": "UNIDADE",
        "ultimopreco": "6.81",
        "quantidadefaturada": 32,
        "participacao": 0.65,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "01/13/2023 00:00:00"
    },
    {
        "codigoproduto": 135902,
        "descricaoproduto": "OLEO SOJA PET 900ML VITALIV",
        "embalagem": "UNIDADE",
        "ultimopreco": "6.38",
        "quantidadefaturada": 40,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "08/07/2023 00:00:00"
    },
    {
        "codigoproduto": 84881,
        "descricaoproduto": "AGUA MINERAL C/GAS 510ML AGUAI",
        "embalagem": "UNIDADE",
        "ultimopreco": "2.29",
        "quantidadefaturada": 132,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "02/06/2024 00:00:00"
    },
    {
        "codigoproduto": 120851,
        "descricaoproduto": "TEMP LEMON E PEPPER 500G NUANCE",
        "embalagem": "PACOTE",
        "ultimopreco": "13.56",
        "quantidadefaturada": 5,
        "participacao": 0.81,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "05/02/2024 00:00:00"
    },
    {
        "codigoproduto": 133681,
        "descricaoproduto": "OLEO ALGODAO 14,5KG ELOGIATA",
        "embalagem": "BALDE",
        "ultimopreco": "173.99",
        "quantidadefaturada": 3,
        "participacao": 0.49,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/03/2025 00:00:00"
    },
    {
        "codigoproduto": 133692,
        "descricaoproduto": "VG BROCOLIS IQF 2KG CG CONFRESCOR",
        "embalagem": "PACOTE",
        "ultimopreco": "17.54",
        "quantidadefaturada": 70,
        "participacao": 1.14,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "11/05/2024 00:00:00"
    },
    {
        "codigoproduto": 81883,
        "descricaoproduto": "PEITO DE FRANGO DEF +-2,4KG RF CERATTI",
        "embalagem": "QUILO",
        "ultimopreco": "45.76",
        "quantidadefaturada": 31,
        "participacao": 1.3,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/30/2025 00:00:00"
    },
    {
        "codigoproduto": 87061,
        "descricaoproduto": "CASTANHA CAJU TRITURADA XEREM FINA 1KG",
        "embalagem": "UNIDADE",
        "ultimopreco": "45.78",
        "quantidadefaturada": 3,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/31/2025 00:00:00"
    },
    {
        "codigoproduto": 133210,
        "descricaoproduto": "CHOC MEIO AMARGO MOEDA 2,05KG MELKEN",
        "embalagem": "UNIDADE",
        "ultimopreco": "116.96",
        "quantidadefaturada": 8,
        "participacao": 1.14,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "06/05/2025 00:00:00"
    },
    {
        "codigoproduto": 134556,
        "descricaoproduto": "FRUTA MORANGO IQF 1,01KG CG CONFRESCOR",
        "embalagem": "QUILO",
        "ultimopreco": "15.99",
        "quantidadefaturada": 12,
        "participacao": 0.81,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/28/2025 00:00:00"
    },
    {
        "codigoproduto": 84144,
        "descricaoproduto": "MOSTARDA DIJON 200G HEMMER",
        "embalagem": "UNIDADE",
        "ultimopreco": "10.19",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "09/15/2022 00:00:00"
    },
    {
        "codigoproduto": 134919,
        "descricaoproduto": "ARROZ ARBORIO 1KG FRITZ E FRIDA NAC",
        "embalagem": "UNIDADE",
        "ultimopreco": "19.81",
        "quantidadefaturada": 180,
        "participacao": 1.62,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "05/28/2024 00:00:00"
    },
    {
        "codigoproduto": 83854,
        "descricaoproduto": "AGUA MINERAL NATURAL 510ML AGUAI",
        "embalagem": "CX C/12 UN",
        "ultimopreco": "1.85",
        "quantidadefaturada": 132,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "02/06/2024 00:00:00"
    },
    {
        "codigoproduto": 84888,
        "descricaoproduto": "AGUA MINERAL C/GAS 510ML INGA",
        "embalagem": "FD C/12 UN",
        "ultimopreco": "2.23",
        "quantidadefaturada": 384,
        "participacao": 0.65,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/23/2025 00:00:00"
    },
    {
        "codigoproduto": 156553,
        "descricaoproduto": "AZEITONA PRETA FAT BD 1,8KG HUBER",
        "embalagem": "BALDE",
        "ultimopreco": "60.33",
        "quantidadefaturada": 2,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/25/2024 00:00:00"
    },
    {
        "codigoproduto": 84750,
        "descricaoproduto": "LEITE PO INTEG 1KG CAMPONESA",
        "embalagem": "UNIDADE",
        "ultimopreco": "42.8",
        "quantidadefaturada": 21,
        "participacao": 0.65,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "05/06/2025 00:00:00"
    },
    {
        "codigoproduto": 85296,
        "descricaoproduto": "FAROFA MILHO 300G PACHA",
        "embalagem": "FD C/20 UN",
        "ultimopreco": "4.34",
        "quantidadefaturada": 60,
        "participacao": 0.49,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "05/21/2025 00:00:00"
    },
    {
        "codigoproduto": 88229,
        "descricaoproduto": "EMB TRUFA/BOMBOM VER 14,5X15,5CM 100UN",
        "embalagem": "UNIDADE",
        "ultimopreco": "9.8",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "02/24/2022 00:00:00"
    },
    {
        "codigoproduto": 113298,
        "descricaoproduto": "QUEIJO CHEDDAR FAT 2.27 KG POLENGHI",
        "embalagem": "PACOTE",
        "ultimopreco": "39.63",
        "quantidadefaturada": 6,
        "participacao": 0.49,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "06/20/2022 00:00:00"
    },
    {
        "codigoproduto": 93525,
        "descricaoproduto": "CAFE TRAD VACUO 500G MELITTA",
        "embalagem": "1X500GR",
        "ultimopreco": "34.49",
        "quantidadefaturada": 3,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "06/30/2025 00:00:00"
    },
    {
        "codigoproduto": 116489,
        "descricaoproduto": "MOSTARDA BIG PUMP 3.3KG CEPERA",
        "embalagem": "UNIDADE",
        "ultimopreco": "29.2",
        "quantidadefaturada": 2,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "05/21/2024 00:00:00"
    },
    {
        "codigoproduto": 133362,
        "descricaoproduto": "CHOC MEIO AMARGO 1,01KG MELKEN",
        "embalagem": "UNIDADE",
        "ultimopreco": "116.96",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/14/2025 00:00:00"
    },
    {
        "codigoproduto": 94566,
        "descricaoproduto": "ESPONJA 75X110MM PCT 10UN SCOTCH BRITE",
        "embalagem": "UNIDADE",
        "ultimopreco": "12.9",
        "quantidadefaturada": 3,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/25/2024 00:00:00"
    },
    {
        "codigoproduto": 103331,
        "descricaoproduto": "CALDO BACON BAG 1,01KG QUALIMAX",
        "embalagem": "UNIDADE",
        "ultimopreco": "13.55",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/12/2024 00:00:00"
    },
    {
        "codigoproduto": 324,
        "descricaoproduto": "ERVILHA 1,7KG BONARE",
        "embalagem": "UNIDADE",
        "ultimopreco": "20.99",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/03/2025 00:00:00"
    },
    {
        "codigoproduto": 118307,
        "descricaoproduto": "FARINHA ARROZ 500G NUANCE",
        "embalagem": "PACOTE",
        "ultimopreco": "3.99",
        "quantidadefaturada": 3,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "06/30/2025 00:00:00"
    },
    {
        "codigoproduto": 86336,
        "descricaoproduto": "GEMA OVO PASTEURIZADO 1L RF FLEISCHEGGS",
        "embalagem": "UNIDADE",
        "ultimopreco": "40.59",
        "quantidadefaturada": 4,
        "participacao": 0.65,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "06/10/2025 00:00:00"
    },
    {
        "codigoproduto": 11216,
        "descricaoproduto": "MOLHO PIMENTA SACHE 252X3ML JUNIOR",
        "embalagem": "UNIDADE",
        "ultimopreco": "37.69",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "08/22/2022 00:00:00"
    },
    {
        "codigoproduto": 158106,
        "descricaoproduto": "AZEITONA PRETA FAT 1,8KG CHEF&CO",
        "embalagem": "UNIDADE",
        "ultimopreco": "64.49",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "08/01/2024 00:00:00"
    },
    {
        "codigoproduto": 3957,
        "descricaoproduto": "REQUEIJAO CREM CULINARIO 1,01KG RF DANUB",
        "embalagem": "UNIDADE",
        "ultimopreco": "26.3",
        "quantidadefaturada": 28,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/28/2022 00:00:00"
    },
    {
        "codigoproduto": 132553,
        "descricaoproduto": "QUEIJO GORGONZOLA +-3KG RF OPERA",
        "embalagem": "QUILO",
        "ultimopreco": "57.87",
        "quantidadefaturada": 6,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "08/18/2022 00:00:00"
    },
    {
        "codigoproduto": 133569,
        "descricaoproduto": "CHOC MEIO AMARGO MOEDA 2,05KG GENUINE",
        "embalagem": "PACOTE",
        "ultimopreco": "153.13",
        "quantidadefaturada": 27,
        "participacao": 4.06,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/08/2025 00:00:00"
    },
    {
        "codigoproduto": 83791,
        "descricaoproduto": "TACINHA P/SOBREMESA C/TAMPA CRIS 10X40ML",
        "embalagem": "UNIDADE",
        "ultimopreco": "7.27",
        "quantidadefaturada": 189,
        "participacao": 4.06,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "05/27/2024 00:00:00"
    },
    {
        "codigoproduto": 82927,
        "descricaoproduto": "DETERGENTE NEUTRO LIQ 5L MARINA",
        "embalagem": "UNIDADE",
        "ultimopreco": "21.7",
        "quantidadefaturada": 7,
        "participacao": 0.81,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "03/23/2023 00:00:00"
    },
    {
        "codigoproduto": 94549,
        "descricaoproduto": "DETERGENTE CLEAR 5L YPE",
        "embalagem": "UNIDADE",
        "ultimopreco": "28.17",
        "quantidadefaturada": 53,
        "participacao": 4.06,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/24/2023 00:00:00"
    },
    {
        "codigoproduto": 113534,
        "descricaoproduto": "COGUMELO FAT 1,01KG CHEFF D CASA",
        "embalagem": "BALDE",
        "ultimopreco": "41.71",
        "quantidadefaturada": 12,
        "participacao": 1.95,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "05/08/2024 00:00:00"
    },
    {
        "codigoproduto": 83869,
        "descricaoproduto": "MASSA C/OVOS ESPAGUETE N8 500G BARIL",
        "embalagem": "UNIDADE",
        "ultimopreco": "4.68",
        "quantidadefaturada": 210,
        "participacao": 0.65,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "05/14/2024 00:00:00"
    },
    {
        "codigoproduto": 9687,
        "descricaoproduto": "LINGUICA CALABRESA RETA 2,5KG RF SEARA",
        "embalagem": "PACOTE",
        "ultimopreco": "26.74",
        "quantidadefaturada": 60,
        "participacao": 1.14,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "06/27/2025 00:00:00"
    },
    {
        "codigoproduto": 120701,
        "descricaoproduto": "TEMP PAPRICA DEF 250G NUANCE",
        "embalagem": "PACOTE",
        "ultimopreco": "6.49",
        "quantidadefaturada": 12,
        "participacao": 0.49,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/28/2025 00:00:00"
    },
    {
        "codigoproduto": 4626,
        "descricaoproduto": "QUEIJO GORGONZOLA AZUL FORMA SAO VICENTE",
        "embalagem": "QUILO",
        "ultimopreco": "94.82",
        "quantidadefaturada": 9,
        "participacao": 0.49,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/10/2025 00:00:00"
    },
    {
        "codigoproduto": 11214,
        "descricaoproduto": "AZEITE OLIVA SACHE 200X4ML JUNIOR",
        "embalagem": "UNIDADE",
        "ultimopreco": "183.25",
        "quantidadefaturada": 9,
        "participacao": 0.81,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "05/28/2025 00:00:00"
    },
    {
        "codigoproduto": 95369,
        "descricaoproduto": "OLEO SOJA PET 900ML SOYA",
        "embalagem": "UNIDADE",
        "ultimopreco": "9.59",
        "quantidadefaturada": 20,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "06/23/2022 00:00:00"
    },
    {
        "codigoproduto": 116111,
        "descricaoproduto": "LEITE UHT INTEG 1L ITAMBE",
        "embalagem": "UNIDADE",
        "ultimopreco": "5.04",
        "quantidadefaturada": 12,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "08/07/2023 00:00:00"
    },
    {
        "codigoproduto": 107278,
        "descricaoproduto": "PEITO DE FRANGO DEF +-2,6KG RF PERDIGAO",
        "embalagem": "QUILO",
        "ultimopreco": "32.9",
        "quantidadefaturada": 10,
        "participacao": 0.49,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "02/06/2025 00:00:00"
    },
    {
        "codigoproduto": 113835,
        "descricaoproduto": "ALCAPARRA 2KG CHEFF D CASA",
        "embalagem": "BALDE",
        "ultimopreco": "76.04",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "08/04/2022 00:00:00"
    },
    {
        "codigoproduto": 88324,
        "descricaoproduto": "CURRY 250G PACHA",
        "embalagem": "UNIDADE",
        "ultimopreco": "3.04",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "05/12/2022 00:00:00"
    },
    {
        "codigoproduto": 157574,
        "descricaoproduto": "ESPONJA LA DE ACO INOX 1UN BETTHAVALE",
        "embalagem": "UNIDADE",
        "ultimopreco": "3.64",
        "quantidadefaturada": 17,
        "participacao": 0.49,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "10/01/2024 00:00:00"
    },
    {
        "codigoproduto": 113831,
        "descricaoproduto": "AZEITONA PRETA FAT 2KG CHEFF D CASA",
        "embalagem": "BALDE",
        "ultimopreco": "61.84",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "01/16/2023 00:00:00"
    },
    {
        "codigoproduto": 85401,
        "descricaoproduto": "COCO FLOCOS INTEG S/ACUCAR 1KG INCOCO",
        "embalagem": "UNIDADE",
        "ultimopreco": "54.49",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/03/2025 00:00:00"
    },
    {
        "codigoproduto": 113946,
        "descricaoproduto": "MOLHO SHOYU PREM SACHE 250X8ML MITSUWA",
        "embalagem": "UNIDADE",
        "ultimopreco": "33.94",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "02/24/2022 00:00:00"
    },
    {
        "codigoproduto": 84822,
        "descricaoproduto": "MASSA P/TAPIOCA PCT 500G DIOKA",
        "embalagem": "UNIDADE",
        "ultimopreco": "5.43",
        "quantidadefaturada": 3,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "12/22/2022 00:00:00"
    },
    {
        "codigoproduto": 156196,
        "descricaoproduto": "VG BROCOLIS PCT 2,5KG CG CONFRESCOR NAC",
        "embalagem": "QUILO",
        "ultimopreco": "19.15",
        "quantidadefaturada": 17,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "01/29/2025 00:00:00"
    },
    {
        "codigoproduto": 136350,
        "descricaoproduto": "PASTA AMENDOIM INTEG 1,005KG VABENE",
        "embalagem": "UNIDADE",
        "ultimopreco": "32.52",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "05/21/2025 00:00:00"
    },
    {
        "codigoproduto": 137104,
        "descricaoproduto": "BATATA SURECRISP 9MM 2,5KG CG MCCAIN N",
        "embalagem": "QUILO",
        "ultimopreco": "21.71",
        "quantidadefaturada": 15,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "02/21/2024 00:00:00"
    },
    {
        "codigoproduto": 116018,
        "descricaoproduto": "QUEIJO GORGONZOLA +-3,5KG RF VIGOR",
        "embalagem": "QUILO",
        "ultimopreco": "101.99",
        "quantidadefaturada": 90,
        "participacao": 3.57,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/16/2025 00:00:00"
    },
    {
        "codigoproduto": 132938,
        "descricaoproduto": "CHOC GOTAS 70% CACAU 1,01KG MELKEN",
        "embalagem": "UNIDADE",
        "ultimopreco": "129.99",
        "quantidadefaturada": 39,
        "participacao": 5.19,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/28/2025 00:00:00"
    },
    {
        "codigoproduto": 103307,
        "descricaoproduto": "MOLHO DEMI GLACE 400G QUALIMAX",
        "embalagem": "UNIDADE",
        "ultimopreco": "33.29",
        "quantidadefaturada": 21,
        "participacao": 1.14,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "06/05/2025 00:00:00"
    },
    {
        "codigoproduto": 95912,
        "descricaoproduto": "AZEITE OLIVA SACHE 200X4G BOM SABOR",
        "embalagem": "CAIXA",
        "ultimopreco": "165.98",
        "quantidadefaturada": 5,
        "participacao": 0.65,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "08/28/2024 00:00:00"
    },
    {
        "codigoproduto": 82242,
        "descricaoproduto": "MOLHO PIMENTA SACHE 175X5G CEPERA",
        "embalagem": "UNIDADE",
        "ultimopreco": "24.88",
        "quantidadefaturada": 6,
        "participacao": 0.97,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "08/26/2024 00:00:00"
    },
    {
        "codigoproduto": 95906,
        "descricaoproduto": "ADOCANTE MAGRO LIGHT SACHE LOWCUCAR",
        "embalagem": "1X1000SH",
        "ultimopreco": "28.17",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/28/2022 00:00:00"
    },
    {
        "codigoproduto": 87388,
        "descricaoproduto": "BATATA PALHA 1KG FRITOP",
        "embalagem": "UNIDADE",
        "ultimopreco": "31.93",
        "quantidadefaturada": 2,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "10/31/2022 00:00:00"
    },
    {
        "codigoproduto": 134955,
        "descricaoproduto": "MASSA PARAFUSO C/OVOS 500G FRITZ E FRIDA",
        "embalagem": "UNIDADE",
        "ultimopreco": "4.08",
        "quantidadefaturada": 40,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "05/16/2024 00:00:00"
    },
    {
        "codigoproduto": 132685,
        "descricaoproduto": "OLEO ALGODAO 14,5KG SOYA",
        "embalagem": "UNIDADE",
        "ultimopreco": "178.99",
        "quantidadefaturada": 4,
        "participacao": 0.49,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "03/24/2025 00:00:00"
    },
    {
        "codigoproduto": 102899,
        "descricaoproduto": "OLEO SOJA PET 900ML LIZA",
        "embalagem": "UNIDADE",
        "ultimopreco": "7.99",
        "quantidadefaturada": 48,
        "participacao": 0.49,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/28/2025 00:00:00"
    },
    {
        "codigoproduto": 159428,
        "descricaoproduto": "ARROZ BRANCO 1KG TUCHE",
        "embalagem": "UNIDADE",
        "ultimopreco": "5.99",
        "quantidadefaturada": 54,
        "participacao": 0.49,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/21/2025 00:00:00"
    },
    {
        "codigoproduto": 84724,
        "descricaoproduto": "MASSA C/OVOS PENNE 500G VILMA",
        "embalagem": "FD C/20 UN",
        "ultimopreco": "4.38",
        "quantidadefaturada": 40,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "05/16/2024 00:00:00"
    },
    {
        "codigoproduto": 85095,
        "descricaoproduto": "SAL REFINADO SACHE 2000X1G ITA",
        "embalagem": "CX C/1 CX",
        "ultimopreco": "27.12",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "11/10/2022 00:00:00"
    },
    {
        "codigoproduto": 113837,
        "descricaoproduto": "TOMATE SECO 1,4KG CHEFF D CASA",
        "embalagem": "BALDE",
        "ultimopreco": "59.99",
        "quantidadefaturada": 2,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "03/13/2025 00:00:00"
    },
    {
        "codigoproduto": 87617,
        "descricaoproduto": "LIMPA ALUMINIO 5L MARINA",
        "embalagem": "UNIDADE",
        "ultimopreco": "28.65",
        "quantidadefaturada": 2,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "02/19/2024 00:00:00"
    },
    {
        "codigoproduto": 157016,
        "descricaoproduto": "CHOC MEIO AMARGO GOTA 70% 1,01KG SICAO",
        "embalagem": "UNIDADE",
        "ultimopreco": "100.83",
        "quantidadefaturada": 2,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "04/17/2025 00:00:00"
    },
    {
        "codigoproduto": 136280,
        "descricaoproduto": "AZEITONA PRETA FAT 2KG OLIVIANA",
        "embalagem": "BALDE",
        "ultimopreco": "72.54",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "03/24/2025 00:00:00"
    },
    {
        "codigoproduto": 83652,
        "descricaoproduto": "FARINHA AVEIA 500G NATUREZA VIVA",
        "embalagem": "UNIDADE",
        "ultimopreco": "9.19",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/21/2025 00:00:00"
    },
    {
        "codigoproduto": 10597,
        "descricaoproduto": "CREME DE CEBOLA SC 1,01KG QUALIMAX",
        "embalagem": "UNIDADE",
        "ultimopreco": "33.37",
        "quantidadefaturada": 8,
        "participacao": 0.32,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "05/13/2024 00:00:00"
    },
    {
        "codigoproduto": 10679,
        "descricaoproduto": "CREME DE CEBOLA 1KG MAGGI",
        "embalagem": "UNIDADE",
        "ultimopreco": "34.99",
        "quantidadefaturada": 2,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "08/21/2023 00:00:00"
    },
    {
        "codigoproduto": 82244,
        "descricaoproduto": "LEITE UHT INTEG 1L UAI",
        "embalagem": "UNIDADE",
        "ultimopreco": "3.99",
        "quantidadefaturada": 24,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "11/09/2022 00:00:00"
    },
    {
        "codigoproduto": 120744,
        "descricaoproduto": "COLORIFICO 1KG NUANCE",
        "embalagem": "PACOTE",
        "ultimopreco": "11.7",
        "quantidadefaturada": 1,
        "participacao": 0.16,
        "mixcliente": null,
        "vendidomes": null,
        "dtultcomp": "07/28/2025 00:00:00"
    }
].slice(0,30)
)});

app.listen(PORT, () => {
  console.log(`🚀 API rodando em http://localhost:${PORT}/produtos`);
});
